version: '3.8'

services:
  oracle:
    image: container-registry.oracle.com/database/enterprise:latest
    environment:
      - ORACLE_SID=ORCLCDB
      - ORACLE_PDB=ORCLPDB1
      - ORACLE_PWD=${ORACLE_PASSWORD}
    ports:
      - "1521:1521"
      - "5500:5500"
    volumes:
      - oracle-data:/opt/oracle/oradata
      - ./init-scripts:/opt/oracle/scripts/setup

volumes:
  oracle-data: