services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: uni-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Uni_Strong_Password_123"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql

volumes:
  sqlserver-data:
